-- Stores in-app notifications created by TwinSure microservices.
-- Each notification belongs to one application user and can be marked as read.
-- Reference fields connect the notification to its originating business record.
CREATE TABLE IF NOT EXISTS NOTIFICATIONS (
                                             notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                             recipient_user_id BIGINT NOT NULL,
                                             notification_type VARCHAR(50) NOT NULL,
    title VARCHAR(150) NOT NULL,
    message VARCHAR(1000) NOT NULL,
    reference_type VARCHAR(50),
    reference_id BIGINT,
    source_service VARCHAR(100) NOT NULL,
    priority VARCHAR(20) NOT NULL,
    read_status BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    read_at TIMESTAMP
    );

CREATE INDEX IF NOT EXISTS idx_notifications_recipient
    ON NOTIFICATIONS(recipient_user_id);

CREATE INDEX IF NOT EXISTS idx_notifications_unread
    ON NOTIFICATIONS(recipient_user_id, read_status);

CREATE INDEX IF NOT EXISTS idx_notifications_reference
    ON NOTIFICATIONS(reference_type, reference_id);