-- Stores simulated AI Twin actions and their evaluation results.
-- Scenario columns preserve the facts used to derive violations.

CREATE TABLE IF NOT EXISTS AI_ACTIONS (
                                          action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          customer_id BIGINT NOT NULL,
                                          twin_id BIGINT NOT NULL,
                                          policy_id BIGINT,
                                          action_type VARCHAR(50) NOT NULL,
    transaction_reference VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500) NOT NULL,
    action_amount DECIMAL(12, 2),
    approval_provided BOOLEAN NOT NULL,
    booking_outcome VARCHAR(50),
    purchase_outcome VARCHAR(50),
    subscription_operation VARCHAR(50),
    cancellation_completed BOOLEAN,
    action_status VARCHAR(50) NOT NULL,
    insured BOOLEAN NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    evaluated_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL
    );

-- Adds scenario columns safely when an older persistent table exists.

ALTER TABLE AI_ACTIONS
    ADD COLUMN IF NOT EXISTS booking_outcome VARCHAR(50);

ALTER TABLE AI_ACTIONS
    ADD COLUMN IF NOT EXISTS purchase_outcome VARCHAR(50);

ALTER TABLE AI_ACTIONS
    ADD COLUMN IF NOT EXISTS subscription_operation VARCHAR(50);

ALTER TABLE AI_ACTIONS
    ADD COLUMN IF NOT EXISTS cancellation_completed BOOLEAN;

-- Stores every distinct violation detected for an action.

CREATE TABLE IF NOT EXISTS ACTION_VIOLATIONS (
                                                 violation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 action_id BIGINT NOT NULL,
                                                 violation_type VARCHAR(50) NOT NULL,
    severity VARCHAR(50) NOT NULL,
    description VARCHAR(500) NOT NULL,
    claim_eligible BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_action_violation
    FOREIGN KEY (action_id)
    REFERENCES AI_ACTIONS(action_id)
    ON DELETE CASCADE,

    CONSTRAINT unique_action_violation
    UNIQUE (action_id, violation_type)
    );