CREATE TABLE IF NOT EXISTS INSURANCE_PRODUCTS (
                                                  product_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  product_code VARCHAR(50) NOT NULL UNIQUE,
    product_name VARCHAR(150) NOT NULL,
    description VARCHAR(500) NOT NULL,
    base_premium DECIMAL(12, 2) NOT NULL,
    coverage_limit DECIMAL(12, 2) NOT NULL,
    deductible DECIMAL(12, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
    );

CREATE TABLE IF NOT EXISTS PRODUCT_COVERAGES (
                                                 coverage_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                 product_id BIGINT NOT NULL,
                                                 action_type VARCHAR(50) NOT NULL,
    violation_type VARCHAR(50) NOT NULL,
    coverage_limit DECIMAL(12, 2),
    active BOOLEAN NOT NULL,
    description VARCHAR(500) NOT NULL,

    CONSTRAINT fk_product_coverage
    FOREIGN KEY (product_id)
    REFERENCES INSURANCE_PRODUCTS(product_id)
    ON DELETE CASCADE,

    CONSTRAINT unique_product_coverage
    UNIQUE (
               product_id,
               action_type,
               violation_type
           )
    );

CREATE TABLE IF NOT EXISTS PRODUCT_EXCLUSIONS (
                                                  exclusion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                  product_id BIGINT NOT NULL,
                                                  exclusion_code VARCHAR(100) NOT NULL,
    description VARCHAR(500) NOT NULL,
    active BOOLEAN NOT NULL,

    CONSTRAINT fk_product_exclusion
    FOREIGN KEY (product_id)
    REFERENCES INSURANCE_PRODUCTS(product_id)
    ON DELETE CASCADE,

    CONSTRAINT unique_product_exclusion
    UNIQUE (
               product_id,
               exclusion_code
           )
    );

CREATE TABLE IF NOT EXISTS POLICY_APPLICATIONS (
                                                   application_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                   customer_id BIGINT NOT NULL,
                                                   twin_id BIGINT NOT NULL,
                                                   product_id BIGINT NOT NULL,
                                                   status VARCHAR(50) NOT NULL,
    risk_score INT,
    risk_level VARCHAR(50),
    system_recommendation VARCHAR(50),
    proposed_premium DECIMAL(12, 2),
    proposed_coverage_limit DECIMAL(12, 2),
    proposed_deductible DECIMAL(12, 2),
    reviewed_by BIGINT,
    decision_reason VARCHAR(500),
    submitted_at TIMESTAMP NOT NULL,
    reviewed_at TIMESTAMP,
    proposal_expires_at TIMESTAMP,
    accepted_at TIMESTAMP,

    CONSTRAINT fk_application_product
    FOREIGN KEY (product_id)
    REFERENCES INSURANCE_PRODUCTS(product_id),

    CONSTRAINT unique_open_twin_application
    UNIQUE (
               twin_id,
               product_id,
               status
           )
    );
CREATE TABLE IF NOT EXISTS POLICIES (
                                        policy_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        policy_number VARCHAR(100) NOT NULL UNIQUE,
    application_id BIGINT NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    twin_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    premium DECIMAL(12, 2) NOT NULL,
    coverage_limit DECIMAL(12, 2) NOT NULL,
    deductible DECIMAL(12, 2) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    cancellation_reason VARCHAR(500),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_policy_application
    FOREIGN KEY (application_id)
    REFERENCES POLICY_APPLICATIONS(application_id),

    CONSTRAINT fk_policy_product
    FOREIGN KEY (product_id)
    REFERENCES INSURANCE_PRODUCTS(product_id)
    );


ALTER TABLE POLICIES
    ADD COLUMN IF NOT EXISTS CANCELLATION_REASON VARCHAR(500);


-- Stores the AI Twin risk configuration captured when a policy is issued.
-- The snapshot remains unchanged even if the current Twin later changes.

CREATE TABLE IF NOT EXISTS POLICY_TWIN_SNAPSHOTS (
                                                     snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                     policy_id BIGINT NOT NULL UNIQUE,
                                                     twin_id BIGINT NOT NULL,
                                                     twin_name VARCHAR(100) NOT NULL,
    autonomy_level VARCHAR(50) NOT NULL,
    transaction_limit DECIMAL(12, 2) NOT NULL,
    approval_threshold DECIMAL(12, 2) NOT NULL,
    twin_status VARCHAR(50) NOT NULL,
    captured_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_policy_twin_snapshot
    FOREIGN KEY (policy_id)
    REFERENCES POLICIES(policy_id)
    ON DELETE CASCADE
    );

-- Stores the action permissions captured together with the Twin snapshot.

CREATE TABLE IF NOT EXISTS POLICY_PERMISSION_SNAPSHOTS (
                                                           permission_snapshot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                           policy_id BIGINT NOT NULL,
                                                           action_type VARCHAR(50) NOT NULL,
    permission_level VARCHAR(50) NOT NULL,
    action_limit DECIMAL(12, 2),
    active BOOLEAN NOT NULL,

    CONSTRAINT fk_policy_permission_snapshot
    FOREIGN KEY (policy_id)
    REFERENCES POLICIES(policy_id)
    ON DELETE CASCADE,

    CONSTRAINT unique_policy_permission_snapshot
    UNIQUE (policy_id, action_type)
    );