spring.application.name=CUSTOMER-SERVICE

server.port=8082

# Persistent Reactive H2 Database
spring.r2dbc.url=r2dbc:h2:file:///./data/customerdb
spring.r2dbc.username=sa
spring.r2dbc.password=

# Execute schema.sql during startup
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Eureka Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Same JWT secret used by Identity Service
jwt.secret=thisismysecuresecretkeyfortwinsurejwtgeneration123456789
jwt.cookie.name=TWINSURE_TOKEN

# Reactive database logging
logging.level.org.springframework.r2dbc=DEBUG
logging.level.io.r2dbc.h2=DEBUG