CREATE TABLE IF NOT EXISTS CUSTOMERS (
                                         customer_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         user_id BIGINT NOT NULL UNIQUE,
                                         full_name VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    address VARCHAR(500) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
    );