package org.example.notificationservice.enums;

public enum NotificationType {

    POLICY_APPLICATION_SUBMITTED,
    POLICY_APPLICATION_APPROVED,
    POLICY_APPLICATION_REJECTED,
    POLICY_CHANGES_REQUIRED,
    POLICY_ISSUED,
    POLICY_CANCELLED,

    AI_ACTION_VIOLATION_DETECTED,

    INCIDENT_REPORTED,

    CLAIM_SUBMITTED,
    CLAIM_ASSIGNED,
    CLAIM_INFORMATION_REQUIRED,
    CLAIM_APPROVED,
    CLAIM_PARTIALLY_APPROVED,
    CLAIM_REJECTED,
    CLAIM_CLOSED,

    GENERAL
}