CREATE TABLE IF NOT EXISTS AI_TWINS (
                                        twin_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        customer_id BIGINT NOT NULL,
                                        twin_name VARCHAR(100) NOT NULL,
    provider_name VARCHAR(100) NOT NULL,
    model_name VARCHAR(100) NOT NULL,
    autonomy_level VARCHAR(50) NOT NULL,
    transaction_limit DECIMAL(12, 2) NOT NULL,
    approval_threshold DECIMAL(12, 2) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT unique_customer_twin_name
    UNIQUE (customer_id, twin_name)
    );

CREATE TABLE IF NOT EXISTS TWIN_PERMISSIONS (
                                                permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                                twin_id BIGINT NOT NULL,
                                                action_type VARCHAR(50) NOT NULL,
    permission_level VARCHAR(50) NOT NULL,
    action_limit DECIMAL(12, 2),
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_twin_permission
    FOREIGN KEY (twin_id)
    REFERENCES AI_TWINS(twin_id)
    ON DELETE CASCADE,

    CONSTRAINT unique_twin_action_permission
    UNIQUE (twin_id, action_type)
    );