-- INCIDENTS
-- Reported event connected to an AI action and active policy.
--
-- CLAIMS
-- Formal insurance claim created from a validated incident.
--
-- CLAIM_DOCUMENTS
-- Evidence metadata supplied for the claim.
--
-- CLAIM_DECISIONS
-- Audit history of every Claims Adjuster decision.

-- Stores an insured incident reported from a violating AI action.
-- It links the Customer, AI Twin, policy, action, and reported financial loss.
CREATE TABLE IF NOT EXISTS INCIDENTS (
                                         incident_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         customer_id BIGINT NOT NULL,
                                         twin_id BIGINT NOT NULL,
                                         policy_id BIGINT NOT NULL,
                                         action_id BIGINT NOT NULL UNIQUE,
                                         incident_type VARCHAR(50) NOT NULL,
    description VARCHAR(500) NOT NULL,
    loss_amount DECIMAL(12, 2) NOT NULL,
    action_occurred_at TIMESTAMP NOT NULL,
    reported_at TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL
    );

-- Stores the formal claim created from one validated incident.
-- It tracks the requested amount, approved amount, assigned adjuster, and workflow status.
CREATE TABLE IF NOT EXISTS CLAIMS (
                                      claim_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                      claim_number VARCHAR(100) NOT NULL UNIQUE,
    incident_id BIGINT NOT NULL UNIQUE,
    customer_id BIGINT NOT NULL,
    twin_id BIGINT NOT NULL,
    policy_id BIGINT NOT NULL,
    action_id BIGINT NOT NULL,
    claimed_amount DECIMAL(12, 2) NOT NULL,
    approved_amount DECIMAL(12, 2),
    deductible_applied DECIMAL(12, 2),
    status VARCHAR(50) NOT NULL,
    assigned_adjuster_id BIGINT,
    submitted_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    closed_at TIMESTAMP,

    CONSTRAINT fk_claim_incident
    FOREIGN KEY (incident_id)
    REFERENCES INCIDENTS(incident_id)
    );

-- Stores metadata about documents or evidence submitted for a claim.
-- The POC stores references and descriptions rather than binary file content.
CREATE TABLE IF NOT EXISTS CLAIM_DOCUMENTS (
                                               document_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               claim_id BIGINT NOT NULL,
                                               document_type VARCHAR(50) NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    document_reference VARCHAR(500) NOT NULL,
    description VARCHAR(500),
    uploaded_by BIGINT NOT NULL,
    uploaded_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_claim_document
    FOREIGN KEY (claim_id)
    REFERENCES CLAIMS(claim_id)
    ON DELETE CASCADE
    );

-- Stores every Claims Adjuster decision as an audit record.
-- A claim can have multiple decisions, such as requesting information and final approval.
CREATE TABLE IF NOT EXISTS CLAIM_DECISIONS (
                                               decision_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                               claim_id BIGINT NOT NULL,
                                               adjuster_id BIGINT NOT NULL,
                                               decision_type VARCHAR(50) NOT NULL,
    previous_status VARCHAR(50) NOT NULL,
    new_status VARCHAR(50) NOT NULL,
    approved_amount DECIMAL(12, 2),
    reason VARCHAR(500) NOT NULL,
    decided_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_claim_decision
    FOREIGN KEY (claim_id)
    REFERENCES CLAIMS(claim_id)
    ON DELETE CASCADE
    );
